services:
  traefik:
    image: "traefik:v3.5"
    command:
      #- "--log.level=DEBUG"
      -  "--log.level=DEBUG" 
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=sumanhazra368@gmail.com"  
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"

    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "letsencrypt:/letsencrypt"
    deploy:
     placement:
       constraints:
         - node.role == manager
    networks:
      - traefik
  AEIE-Club-client:
    image: "sumanhazra914/aeie_club_client:latest"
    deploy:
      mode: replicated
      replicas: 2
    labels:
     - "traefik.enable=true"
      # frontend â†’ default catch-all (everything except /api)
     - "traefik.http.routers.aeie-client.rule=Host(`aeie.localhost`)"
     - "traefik.http.routers.aeie-client.entrypoints=websecure"
     - "traefik.http.routers.aeie-client.tls.certresolver=myresolver"
     - "traefik.http.services.aeie-client.loadbalancer.server.port=80"
    networks:
      - traefik
  AEIE-Club-Server:
    image: "sumanhazra914/aeie_club_server:latest"
    environment:
    - DB_URL=mongodb+srv://sumanhazra368:tDnqBItGtxlrb0TL@aeiecluster0.lt2akvi.mongodb.net/?retryWrites=true&w=majority&appName=AEIEcluster0
    - IMAGEKIT_PUBLIC_KEY=public_IdL2aCe8j0dEwXVT5LNygLDQ3XE=
    - IMAGEKIT_PRIVATE_KEY=private_pZmWx4fmNC99DJIn7OFyv854ud0=
    - IMAGEKIT_URL_ENDPOINT=https://ik.imagekit.io/AEIE
    - JWT_SECRET=441274548542
    - PORT=3000
    deploy:
      mode: replicated
      replicas: 3
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.AEIE-server.rule=Host(`aeie.localhost`) && PathPrefix(`/api`)"
    - "traefik.http.routers.AEIE-server.entrypoints=web"
    - "traefik.http.services.AEIE-server.loadbalancer.server.port=3000"
    networks:
      - traefik

      
networks:
  traefik:
    driver: bridge  
volumes:
    letsencrypt:   